title:              imjisu
email:              imjisu883508@gmail.com
description:        
author:             Hongjun Na
baseurl:            ""
url:                "https://imjisu883508.github.io/"
twitter_username:   
github_username:    imjisu883508
facebook_username:  
instagram_username:  
linkedin_username:
google_analytics:   UA-XXXXXXXXX-X 
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
