title:              Im_jisu
email:              imjisu883508@gmail.com
description:        안녕하세요! 빵 굽는 개발자 Jisu 입니다.
author:             Hongjun Na
baseurl:            ""
url:                "https://imjisu883508.github.io/WIGIT/"
twitter_username:   
github_username:    imjisu883508
facebook_username:  
instagram_username:  
linkedin_username:
google_analytics:   UA-XXXXXXXXX-X 
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
